update dpemote with keybinds
qbcore-framework/dpemotes pull request #15
Opened 2021-09-20 08:01 UTC by evanillaa

2021-09-20 08:28 UTC, evanillaa commented
low ms

2021-09-21 00:06 UTC, phumberdroz requested changes
Generally there is a couple of things that could be improved. (see my comments)

Also it would be nice to get some annotation in regards to your motivation to do a certain change.

Overall I am uncertain about adding your name to the function headers as git keeps track of those changes, but that is up to the Project Maintainers to decide.

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["batery"] = {"anim@heists@humane_labs@finale@keycards", "ped_a_enter_loop", "Mechanik - Baterie", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["plate"] = {"amb@world_human_tourist_map@male@base", "base", "Mechanik - Plate", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["bumper"] = {"anim@heists@box_carry@", "idle", "Mechanik - Nárazník", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["hood"] = {"anim@heists@box_carry@", "idle", "Mechanik - Kapota", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["door"] = {"anim@heists@box_carry@", "idle", "Mechanik - Dvere", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["exhaust"] = {"missheistdocksprep1hold_cellphone", "static", "Mechanik - Výfuk", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["carseat"] = {"anim@heists@box_carry@", "idle", "Mechanik - Sedacka", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["wheel"] = {"anim@heists@box_carry@", "idle", "Mechanik - Kolo", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   ["engine"] = {"anim@heists@box_carry@", "idle", "Mechanik - Motor", AnimationOptions =
Would you mind translating this to English? :)

2021-09-21 00:06 UTC, phumberdroz commented on Client/AnimationList.lua
> +   }},
```suggestion
   }},
```

2021-09-21 00:06 UTC, phumberdroz commented on Client/Emote.lua
> +  end
```suggestion
  end
```

2021-09-21 00:06 UTC, phumberdroz commented on Client/Emote.lua
> +end]]
You could consider removing the entire function

2021-09-21 08:50 UTC, evanillaa reviewed
y

2021-09-22 14:37 UTC, closed without merging